### ISSUE TITLE
Automate conversion from spatialite to mbtiles

### ISSUE THREAD

**Issue by bmehta** [mapbox/mapbox-studio-classic#1511] opened 2015-12-07 21:28 UTC
I have successfully been able to use Mapbox Studio Classic to import spatialite and convert it to mbtiles. If I wanted to automate this, what source code should I be looking at? Does Mapbox Studio use something like Mapnik to do this conversion?

Thanks.

**Comment by wilhelmberg** [comment] 2015-12-14 10:17
duplicate of https://github.com/mapnik/node-mapnik/issues/571

**Closed as completed by wilhelmberg** 2015-12-14 10:17 UTC
