### ISSUE TITLE
saving tmp style crashes app

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#163] opened 2014-03-05 22:39 UTC
if you try to save or export a style that has not been saved as `.tm2` directory, app throws this error and crashes

```
stream.js:94                                      
      throw er; // Unhandled stream error in pipe.
            ^                                     
Error: ENOENT, lstat '/tmp-994644ba' 
```

**Comment by springmeyer** [comment] 2014-03-05 22:43
dupe of #104

**Closed as completed by springmeyer** 2014-03-05 22:43 UTC
