### ISSUE TITLE
Create style from remote source broken in 0.2.6

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#1250] opened 2015-03-13 11:52 UTC
When using the 'create style from source' and selecting the newly-created remote source, v0.2.6 creates a default 'Mapbox Street v5' project rather than using the requested remote source layer. Everything worked fine in 0.2.5.

**Comment by samanpwbb** [comment] 2015-03-13 16:24
I can confirm that this is happening with the app. I'm sure it was introduced with https://github.com/mapbox/mapbox-studio/pull/1232

**Comment by samanpwbb** [comment] 2015-03-13 16:46
When running Studio in the browser, this is not an issue. 

I thought this was related to https://github.com/mapbox/mapbox-studio/pull/1232 but the route to create a new style from source uses `newStyle` and should be unchanged by the PR: https://github.com/mapbox/mapbox-studio/blob/8f4992d1739570a83f1c4dbc4702ea39b0009b02/lib/middleware.js#L78-L86

@camilleanne do you have any idea what's up here?

**Comment by amyleew** [comment] 2015-03-17 22:09
@samanpwbb still an issue in browser for me.

**Comment by samanpwbb** [comment] 2015-03-17 22:12
I'll try to look into this more later this week.

**Comment by camilleanne** [comment] 2015-03-17 22:47
Took a quick stab at this and found:
1) In the packaged version of `v0.2.6` I downloaded from mapbox.com, I can reproduce this with both `local` and `remote` sources regardless of how many times I've attempted to create a new source from a style (same source every time)
2) If I run Mapbox Studio pulled from `mb-pages` checked out at either latest _or_ `v0.2.6` with the same version of `atom-shell` that we're currently packaging Mapbox Studio with ([`0.21.1`](https://github.com/mapbox/mapbox-studio/blob/mb-pages/.travis.yml#L12)), I cannot reproduce the error.

Not sure what this means, but maybe there is something about our packaging process that went awry. Also, the links to the creation of a new style from local and remote sources look correct:

![screen shot 2015-03-17 at 3 28 06 pm](https://cloud.githubusercontent.com/assets/3952537/6699200/ed8255ca-ccbc-11e4-97e4-da985b0a30f2.png)

**Comment by springmeyer** [comment] 2015-03-18 06:35
> Not sure what this means, but maybe there is something about our packaging process that went awry. 

Odd: what about pushing a new test build from a branch tomorrow and see if it suffers from the problem? I looked through `build-atom.sh` tonight and don't see anything obvious that would cause the packaged build to behave differently. I notice we pass `--production` to the `npm install` but that should not matter...

**Comment by mtirwin** [comment] 2015-03-18 14:19
Able to reproduce. Studio (program not browser) keeps the Mapbox Streets v5 css style even when I change the source ID.

**Comment by amyleew** [comment] 2015-03-18 19:38
@camilleanne @springmeyer 

@mtirwin and I found a work around in Studio, launch a template style then add layer as local source and connects just fine. Maybe it's not an atom issue?

![image](https://cloud.githubusercontent.com/assets/4587826/6717677/b0ab9472-cd84-11e4-8a28-4eda5caa76a5.png)

**Comment by camilleanne** [comment] 2015-03-19 00:09
@springmeyer and I figured it out -- the space in `Mapbox Studio.app` in the working directory of the packaged app turns into `Mapbox%20Studio.app` here: https://github.com/mapbox/mapbox-studio/commit/b064544dbdaf07e367411df343b773723547c1c5#diff-d7dfcb350720309421bbb465055aafdfR169.

This should be not a big deal to fix, however, it's indicative of a larger problem with middleware silently failing. The middleware can't load the correct style, so it fails silently and defaults to the `tmp` style.

I will do a more vigorous evaluation of where we need url.format, and see if I can errors coming through for stuff like this.

**Comment by yhahn** [comment] 2015-03-19 12:00
@camilleanne @springmeyer thanks for tracking this down.

Because we're using project filepaths as IDs it's critical that there's only one way to represent a path internally to the same project.

Instead of using `url.format` everywhere I've sketched out an approach where a very early middleware is used to unencode any escaped URL params and normalize paths for windows discrepancies -- see here https://github.com/mapbox/mapbox-studio/compare/single-pathnormalizer.

Would be curious to know if you have any ideas for testing this issue in an integrated way -- maybe a low hanging first line of defense would be to have travis rename the repo from `mapbox-studio` to `mapbox studio` before running the tests...

**Comment by amyleew** [comment] 2015-03-19 14:26
thanks for tracking this down @springmeyer @camilleanne

**Comment by mtirwin** [comment] 2015-03-19 14:34
Goodbye :bug:.

![](http://i.giphy.com/ZxrpYTevDLmmY.gif)

**Comment by springmeyer** [comment] 2015-03-23 07:54
noting: my understanding is that this should be fixed by #1267. But in testing #1267 I hit another one: #1278

**Comment by springmeyer** [comment] 2015-03-23 20:05
fixed by #1267

**Closed as completed by springmeyer** 2015-03-23 20:05 UTC
Labels: bug
