### ISSUE TITLE
Can't stop TM2 with Ctrl-c after exporting source

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#69] opened 2013-10-17 20:43 UTC
After exporting a source MBTiles from TM2 (or starting one then cancelling it), I can no longer stop the server with ctrl-c.

**Comment by springmeyer** [comment] 2014-02-26 19:45
ha, also just hit this.

**Comment by springmeyer** [comment] 2014-03-06 22:55
https://github.com/mapbox/tilelive-vector/issues/41 should be fixed but does not appear to be the cause of this problem.

**Comment by ian29** [comment] 2014-04-02 22:03
looks like this is still occurring as of 98f3273

**Comment by springmeyer** [comment] 2014-04-23 04:05
still occurring in master. workaround either with `killall tm2` in another terminal or with this nuclear patch:

``` diff
diff --git a/lib/tm.js b/lib/tm.js
index c7d5fef..f7e93e3 100644
--- a/lib/tm.js
+++ b/lib/tm.js
@@ -14,6 +14,10 @@ tilelive.protocols['mbtiles:'] = require('mbtiles');

 var tm = {};

+process.on('SIGINT', function() {
+    process.exit(0);
+});
+
 // Set or get config.
 tm.db;
 tm._config = {
```

**Comment by yhahn** [comment] 2014-06-27 04:52
Fixed via tilelive upgrade.

**Closed as completed by yhahn** 2014-06-27 04:52 UTC
