### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by btcnash** [mapbox/mapbox-studio-classic#730] opened 2014-08-27 02:04 UTC
Mapbox Studio @ http://localhost:3000/
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/Users/elankey/Documents/GitHub/mapbox-studio/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.res.set.res.header (/Users/elankey/Documents/GitHub/mapbox-studio/node_modules/express/lib/response.js:518:10)
    at ServerResponse.res.cookie (/Users/elankey/Documents/GitHub/mapbox-studio/node_modules/express/lib/response.js:590:8)
    at done (/Users/elankey/Documents/GitHub/mapbox-studio/lib/server.js:172:17)
    at cb (/Users/elankey/Documents/GitHub/mapbox-studio/node_modules/tilelive-vector/index.js:124:20)
    at /Users/elankey/Documents/GitHub/mapbox-studio/node_modules/tilelive-vector/backend.js:161:29

**Comment by tmcw** [comment] 2014-08-27 16:19
Duplicate of #645

**Closed as completed by tmcw** 2014-08-27 16:19 UTC
