### ISSUE TITLE
Cannot Pan/Zoom On Loaded Data

### ISSUE THREAD

**Issue by Brideau** [mapbox/mapbox-studio-classic#1254] opened 2015-03-17 00:57 UTC
I'm new to MapBox Studio and was giving the [Quickstart](https://www.mapbox.com/mapbox-studio/source-quickstart/) a try to see if I could get that to work. I can get as far as loading the Earthquake data and clicking "Done", but it doesn't allow me to do anything after that. The screen just stays here and doesn't allow me to pan/zoom:

![screen shot 2015-03-16 at 9 51 29 pm](https://cloud.githubusercontent.com/assets/844397/6679454/a015d654-cc26-11e4-9f5b-3473889ca7d3.png)

At one point, after some random clicking of the +/-/full-screen buttons it came to life and let me pan and zoom, but then I tried restarting it to see if I could repeat it but haven't had any luck.

I've tried installing older versions back to 1.6 and running them off localhost in different browsers with the same results. I also tried deleting ~/Library/Application Support/mapbox-studio/ and ~/.mapbox-studio/app.db but that didn't help either.

My machine is a late 2013 MacBook Pro running Yosemite 10.10.2

**Comment by Brideau** [comment] 2015-03-17 01:58
Update:
When I run the network profiler in chrome while clicking around, I notice that each click is making a GET request to: _http://localhost:3000/source/3,21.09375,-4.390228926463384.json?id=tmpsource:///[A bunch of my directories]/mapbox-studio-0.2.6/node_modules/mapbox-studio-default-source&bf3e06c6_ that returns an empty object.

I have also found a way to get it working consistently: right after I load the CSV file, if I refresh the page, it works. After that, the GET requests return tiles as expected.

**Comment by springmeyer** [comment] 2015-03-17 02:15
@Brideau - thanks for your research. So to confirm: you see this even in chrome or firefox if you load up http://localhost:3000 ?. When it happens next can you open up Activity Monitor and check to see if the processes named `mapbox-studio` are doing anything significant in terms of CPU (or whether they appear idle)?

**Comment by Brideau** [comment] 2015-03-17 02:20
Yes, I've tried it in both Chrome v40 and Firefox v35 with the same result loading it from http://localhost:3000 and the mapbox-studio process is completely idle.

**Comment by Brideau** [comment] 2015-03-17 12:42
Another update: I had a friend reproduce the same issue on a 2012 MacBook Pro also running Yosemite, so perhaps its a OS X specific problem?

**Comment by rclark** [comment] 2015-03-17 12:55
@GretaCB and I encountered this yesterday. It appeared to be dataset-dependent for me, although I believe @GretaCB saw this happen for any data she threw at it. For me, a particular TIF file exhibited this behavior, but another geojson file did not.

Will investigate more today and try to pin down a reproducible example.

**Comment by GretaCB** [comment] 2015-03-18 00:19
I was seeing this behaviour for all files I tried. This bug seemed odd to me because I wasn't experiencing it a few weeks ago on `mb-pages` branch. Today I tried out versions all the way back to mid-february to see if I could corner a particular commit, but the bug didn't go away.

Per chat with @rclark , tried to corner possible Leaflet incompatibilities and ended up [creating a branch](https://github.com/mapbox/mapbox-studio/tree/new-mapboxjs) that updates the mapbox.js ext, which dated back to last summer. This solved the issue. I'm wondering if this has less to do with a particular code change on our side, and more on just outdated extension/dependency.

cc @springmeyer

**Comment by Brideau** [comment] 2015-03-18 04:19
@GretaCB Tried installing and running your branch, but it didn't seem to fix the problem on my end by the looks of it unfortunately.

**Comment by Brideau** [comment] 2015-03-20 12:52
@springmeyer Any update on this? Right now I can't use MapBox Studio on any of my machines which is holding up a few projects.

**Comment by samanpwbb** [comment] 2015-03-20 14:08
1. I tested with a handful of `shp` files (ranging from 1 MB to 100 MB) and `geojson` files (ranging from a few KB to a few MB). Problem occurred with 2 of the shp files, one 3.8MB and one 326KB. Not consistently, and for varying amounts of time (sometimes unresponsiveness would last until i quit, sometimes just a couple seconds). Didn't run into the problem with the larger shape files.
2. Only the map is unresponsive.
3. I did some performance profiling in the browser, and there seem to be no ongoing processes that are holding things up.
4. Refreshing the page, closing and opening the app, or just waiting a long time after importing a style fixes the issue.

Here are the shapefiles that I consistently had problems with: https://www.dropbox.com/s/vkwcg6paq7tuz7k/stalling-shapefiles.zip?dl=0

**Comment by rclark** [comment] 2015-03-20 16:57
Little bits of info trickling in as I'm debugging:
- @samanpwbb I can recreate the issue with your shapefiles
- I'm noticing that when the `ne_10m_lakes` is added to the map, there's a call made to:
  `js
  map.setView([15.64277067591253, 5.594398736198173], 1);
  `
  ... but the zoom / center of the map remains unchanged: `[0, 0], 3`. No `viewreset` or `move` events are fired.
- clicking the `+` and `-` buttons then fires subsequent `.map.setView` calls based on the map's unchanged center/zoom. i.e. `+` tries to set the view to `[0, 0], 4`.

**Comment by samanpwbb** [comment] 2015-03-20 22:39
I have a good fix in place here: https://github.com/mapbox/mapbox-studio/pull/1270 - but it'd be nice to know this is actually covered by tests.

@rclark I tried triggering this bug via tests, and no luck. Here's my attempt:
https://github.com/mapbox/mapbox-studio/tree/map-test

I tossed a shp file i know has issues (http://cl.ly/0l402E2B2t29) into `node_modules/mapnik-test-data/data/shp` and even that fixture passed my tests.

Any tips?

**Closed as completed** 2015-03-22 17:08 UTC

**Comment by springmeyer** [comment] 2015-06-19 01:23
dropping by to say I can still replicate a 3-4 second hang using http://cl.ly/0l402E2B2t29 if animation is enabled with fitBounds. Also I though #1388 might be related but the 3-4 second hang still happens with the fix for #1388 (clamping bounds to valid wgs84 range) when animation is on.
