### ISSUE TITLE
SQLITE_CANTOPEN on startup/auth

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#654] opened 2014-08-13 15:58 UTC
From a user running windows build fcaf7c2

> I’m running into an issue where I can navigate past the Authorize Your Account page.
> 
> If I chose “Allow” and then “Skip Intro” I get this error:
> 
> ![image](https://cloud.githubusercontent.com/assets/1056106/3908263/085f9bc4-2302-11e4-8e58-d8d91e52b73c.png)
> 
> If I chose “Deny” than I get this error:
> 
> ![image](https://cloud.githubusercontent.com/assets/1056106/3908272/197acfb4-2302-11e4-8be5-18b774c74a10.png)
> 
> Clicking on the “X” just navigates me back to the Login page.
> I’ve tried revoking the MBS access token in my account settings and having MBS add in the token, but that’s not working either.

**Comment by tjperry07** [comment] 2014-08-22 21:16
Same issue on Windows

**Comment by KcKal** [comment] 2014-09-01 04:12
Ditto on this problem. Windows 8.

**Comment by yhahn** [comment] 2014-09-01 04:15
@KcKal any chance you could gist your logs like you did here? https://github.com/mapbox/mapbox-studio/issues/737#issuecomment-53990331

Thanks in advance.

**Comment by KcKal** [comment] 2014-09-01 04:23
Easy. Unfortunately though, not a whole lot of info in the log file:

https://gist.github.com/KcKal/7bc399075daa59028ca5

**Comment by yhahn** [comment] 2014-09-01 04:37
Hrm, looking into this and seeing a few possible culprits (http://sqlite.1065341.n5.nabble.com/Random-error-SQLITE-CANTOPEN-on-Windows-XP-SP2-with-sqlite3-exec-td10529.html), in particular:
- TortoiseSVN
- Antivirus scanners

If you're running anything like this that might be scanning/reading these files it would be great to know if the issue occurs when they are disabled -- not as a long term solution but to confirm the source of the problem.

**Comment by KcKal** [comment] 2014-09-01 04:53
Don't have TortoiseSVN, and only have the lameass "Windows Defender" that comes with Windows 8. Turned that badboy off as well, to no avail.

**Comment by yhahn** [comment] 2014-09-01 04:54
Nice : ) thx for the datapoints -- will keep digging.

**Comment by KcKal** [comment] 2014-09-01 05:00
No worries. Got a new product/project launch for which studio would be rather perfect so I'm pretty keen to get into it. :)

**Comment by yanaybrook** [comment] 2014-09-01 09:26
Got the same issue. Windows 8

**Comment by wilhelmberg** [comment] 2014-09-01 12:01
Windows 8:
I just get `Access denied` error.

app.log:

```
Mapbox Studio @ http://localhost:3000/
Error: Access denied
    at Object.app.use.passport.authenticate.session [as handle] (c:\Program Files (x86)\mapbox-studio\resources\app\lib\oauth.js:62:14)
    at next (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\node_modules\connect\lib\proto.js:190:15)
    at next (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\node_modules\connect\lib\proto.js:165:78)
    at next (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\node_modules\connect\lib\proto.js:165:78)
    at Object.initialize [as handle] (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\passport\lib\middleware\initialize.js:62:5)
    at next (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\node_modules\connect\lib\proto.js:190:15)
    at Object.expressInit [as handle] (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\middleware.js:31:5)
    at next (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\node_modules\connect\lib\proto.js:190:15)
    at Object.query [as handle] (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\node_modules\connect\lib\middleware\query.js:44:5)
    at next (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\node_modules\connect\lib\proto.js:190:15)
```

**Comment by wilhelmberg** [comment] 2014-09-01 12:03
W8: If I start MapBox Studio as Administrator it works.

**Comment by wilhelmberg** [comment] 2014-09-01 12:04
2nd run as normal user is successful.

**Comment by wilhelmberg** [comment] 2014-09-01 12:24
W7: No problems.

Interesting thing:
I deleted `c:\Program Files (x86)\mapbox-studio` and `~/.mapbox-studio` before installing 0.0.6 and it still knows my user name.

**Comment by springmeyer** [comment] 2014-09-02 17:15
noting that there was [this bug](https://github.com/mapbox/node-sqlite3/pull/283) in node-sqlite3 but as far as I can see neither mbstudio or node-mbtiles is using `sqlite3.cached.Database()`.

**Comment by springmeyer** [comment] 2014-09-02 17:35
good description, if old, of one cause of this problem: http://svn.haxx.se/dev/archive-2003-10/0136.shtml

**Comment by pmwalker1990** [comment] 2014-09-03 18:05
First time trying to open Mapbox Studio, got this error. Haven't successfully opened the software at all, unfortunately.

**Comment by wilhelmberg** [comment] 2014-09-03 18:16
@pmwalker1990 
Have you tried starting it as Admin?
`Right click -> Run as Adminstrator`
For then on I could run it normally.

**Comment by wilhelmberg** [comment] 2014-09-03 18:18
Update from my side:
In the meantime I've tried it with vanilla installs (all 64bit) of
- W8
- W8 SP1
- W8.1

No errors.

**Comment by pmwalker1990** [comment] 2014-09-03 19:18
Just did a fresh install and tried opening as admin, still getting the same error. Unfortunately, I'm new to the community, so I'm still learning how everything works. In other words, I don't have much to offer in terms of troubleshooting the problem.

**Comment by KcKal** [comment] 2014-09-04 00:29
I tried that, but didn't work for me. W8.1
ᐧ

**Comment by MarkWS** [comment] 2014-09-04 15:33
Update:
Myself and Ian (at MapBox) started this thread.
I spent about two hours yesterday trying to figure out why MapBox Studio (MBS) is not referencing the SQLite DB that is loaded with the software.

Our findings:
• We tweaked the mbtiles.js and the node.js  file constructor. In the node.js we modified line 54 and 55 if 'err return path' instead of 'err object' which is as most of you know is 'SQLITE_CANTOPEN'
• That returned the actual path or file that SQLite is looking for.
• It seems it’s looking for a DB file in the cache folder;  \Users\user-name.mapbox-studio\cache  which does not exits;  very-long-file-name.mbtiles
• We created a blank file, placed that in the folder but still nothing
Today we will create a blank SQLite DB file, rename it to the file name MBS is looking for, and try again.

Updating the permissions in the cache folder;  \Users\user-name.mapbox-studio\cache  returned no positive results

Win 7 Pro 64bit

**Comment by yhahn** [comment] 2014-09-04 15:53
@MarkWS thanks for your detailed notes -- we've been looking into this over the past few days and your report is giving me some ideas for more things to try. Will keep you posted.

**Comment by yhahn** [comment] 2014-09-04 16:39
@MarkWS we're looking at this now and it's def not fixed in 0.0.7. At least one possible cause of this is having a _username folder with a space or other non alphanumeric characters in it_. I think we'll have a fix for this shortly but if you want to test this hypothesis (by using a username without a space character) it would be very helpful.

**Comment by MarkWS** [comment] 2014-09-04 16:52
Yes, still not working with v0.7 and this is the error:

![capture](https://cloud.githubusercontent.com/assets/8440284/4152978/bf7cbfe6-3453-11e4-8c10-49fdbc37b4a4.JPG)

I see the path is now being displayed, which is nice. At least we know where the problem is occurring.

**Comment by yhahn** [comment] 2014-09-04 16:53
@MarkWS great, will have a v0.0.8 for you to test later today.

**Comment by yhahn** [comment] 2014-09-04 22:51
@MarkWS and others -- there's a new v0.0.8 release for windows available here:

https://www.mapbox.com/mapbox-studio/#win32

It has an important fix that may address this issue in some cases and have better error messages that will help us track down remaining issues if not. Let me know how it goes for you!

**Comment by MarkWS** [comment] 2014-09-05 14:20
v0.0.8 seems to have solved this problem.
I can now start MBS!
Thanks Young!

**Comment by yhahn** [comment] 2014-09-05 16:25
@KcKal @pmwalker1990 @tjperry07 @yanaybrook would be great if you could try the new release out and confirm (or deny) the fix.

**Comment by pmwalker1990** [comment] 2014-09-06 01:42
Everything is working now! Thank you so much! Can't wait to start using it.

**Comment by yanaybrook** [comment] 2014-09-07 10:18
Its working also for me... seems to solve the problem.
Thanks a lot for your help... Will create some awesome maps now :)

**Comment by yhahn** [comment] 2014-09-07 12:05
Great, closing.

**Closed as completed by yhahn** 2014-09-07 12:05 UTC
Labels: windows
