### ISSUE TITLE
Failed login saved (oauth error)

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#1128] opened 2015-01-14 22:14 UTC
Login error with Studio when failed user login is saved. 

``` sql
500 'GET' '/oauth/mapbox?error=Cannot_read_property_%27accountLevel%27_of_undefined' 'AuthorizationError'

```

cc @springmeyer

**Comment by willwhite** [comment] 2015-01-15 22:33
Appears to be a duplicate of https://github.com/mapbox/mapbox-studio/issues/1129.

**Closed as completed by willwhite** 2015-01-15 22:33 UTC
Labels: bug
