### ISSUE TITLE
Vector tile load error

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#214] opened 2014-03-14 19:17 UTC
Got this error twice today:

```
  /Users/nickidlugash/work_repos/tm2/node_modules/express/lib/router/index.js:146
        var fn = paramCallbacks[paramIndex++];
                           ^
  TypeError: Cannot read property '0' of undefined
  at paramCallback (/Users/nickidlugash/work_repos/tm2/node_modules/express/lib/router/index.js:146:30)
   at done (/Users/nickidlugash/work_repos/tm2/index.js:65:16)
   at Vector.done (/Users/nickidlugash/work_repos/tm2/lib/style.js:80:16)
   at Vector.g (events.js:180:16)
   at Vector.EventEmitter.emit (events.js:98:17)
   at /Users/nickidlugash/work_repos/tm2/node_modules/tilelive-vector/index.js:40:40
    at /Users/nickidlugash/work_repos/tm2/node_modules/tilelive-vector/index.js:94:24
    at setsource (/Users/nickidlugash/work_repos/tm2/node_modules/tilelive-vector/backend.js:54:23)
   at /Users/nickidlugash/work_repos/tm2/node_modules/tilelive-vector/backend.js:36:17
   at CachingSource.TileJSON.getInfo (/Users/nickidlugash/work_repos/tm2/node_modules/tilejson/lib/tilejson.js:131:10)
  Segmentation fault: 11
```

**Comment by nickidlugash** [comment] 2014-03-14 19:25
Gist with application crash file: https://gist.githubusercontent.com/nickidlugash/3d2a7686a7d20ff61cd1/raw/946a6bd1671a35c046ef2f29134a9a07cf989ba8/tm2-crash-2.md

**Comment by nickidlugash** [comment] 2014-03-14 19:39
Last commit for the version I source installed:

commit 7d1d405b8ce61f848af3aa518eeaaedb19e82083
Author: samanpwbb samanpwbb@gmail.com
Date:   Mon Mar 10 12:05:42 2014 -0400

```
use cmd+, for layers sidebar, refs #130
```

**Comment by springmeyer** [comment] 2014-03-17 20:43
@nickidlugash - Curious: have you seen this again yet?

**Comment by nickidlugash** [comment] 2014-03-17 21:10
@springmeyer no, have not seen it again.

As of this morning, this is the last commit for the version I'm using:

commit 4ad9fcdff0537f6adf1aabc307bef21c3628512f
Merge: a62b115 e08df12
Author: tristen tristen@tristen.ca
Date:   Mon Mar 17 11:10:32 2014 -0400

```
Merge pull request #217 from mapbox/swatches

Swatches
```

**Comment by springmeyer** [comment] 2014-04-02 21:44
another report from @makella: https://gist.github.com/makella/e1c76b604f541cc05bc6. Looks like the common problem is `mapnik::freetype_engine::create_face`, so I think this must have something to do with a font that is being read and Mapnik is not reading it correctly and memory is being corrupted.

**Comment by makella** [comment] 2014-04-02 21:50
@springmeyer I am using a custom font, Frutiger, for all features on the map.
I am not running any exports on my machine.  The only pattern I've noticed so far is that it happens when I change something and hit Save.  It just happened again when I changed the `text-size` property for a feature.  I'll keep better track of what I'm doing when it happens from here on out and comment back here.

**Comment by springmeyer** [comment] 2014-04-02 22:01
> The only pattern I've noticed so far is that it happens when I change something and hit Save

Really? Interesting and good info. So you've not seen is when simply browsing? Only recently after a save?

I though I heard from you earlier that this crash happened during an export? Did I get that wrong? Or maybe it happened right at the start of an export perhaps? (which would be after loading the map, like a save).

**Comment by springmeyer** [comment] 2014-04-02 22:03
btw, how many MB is `Frutiger`?

**Comment by makella** [comment] 2014-04-02 22:08
Yeah, sorry for the confusion. 

On the other machine where we're doing the majority of the exports, that's where we were getting kicked out of TM2 with the Abort Trap: 6 error.  In that case, TM2 was only exporting nothing else.

On my machine, I'm only designing nothing else.  This is the one that is giving me the font issue that you mention above.

It may have been due to panning but I didn't realize it until I hit save?  Does that make sense?

Frutiger is 270 KB

**Comment by springmeyer** [comment] 2014-04-02 22:46
Okay, great, thanks that is all clear now. So, abort trap is due to postgres wait. This crash appears related to fonts, but if Frutiger is so small, my hunch is that its actually related to map loading (which happens after saving). I'm working on a workaround over at https://github.com/mapbox/tilelive-vector/issues/45

**Comment by mojodna** [comment] 2014-04-02 22:52
I see this not infrequently, but typically with different stack traces (all of which appear to point at Express).  Here's the most recent one I've seen:

```
TypeError: Cannot read property '0' of undefined
    at paramCallback (/Users/seth/src/mapbox/tm2/node_modules/express/lib/router/index.js:146:30)
    at load (/Users/seth/src/mapbox/tm2/index.js:170:52)
    at /Users/seth/src/mapbox/tm2/index.js:185:13
    at /Users/seth/src/mapbox/tm2/lib/source.js:319:29
    at Get.<anonymous> (/Users/seth/src/mapbox/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:287:25)
    at Get.<anonymous> (/Users/seth/src/mapbox/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:169:29)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
```

**Comment by springmeyer** [comment] 2014-04-02 23:01
@mojodna - thanks for the details. I've not paid any attention to the node.js stack trace myself because of the segfault in Mapnik that is also happening. I'm assuming that the segfault is the cause and not the result. But this may be an incorrect assumption.

**Comment by mojodna** [comment] 2014-04-02 23:04
I don't see corresponding segfaults, FWIW (my stacks usually don't touch mapnik when tm2 crashes).

**Comment by springmeyer** [comment] 2014-04-02 23:11
@mojodna interesting. Can you say more: on what OS are you seeing this error but with no segfaults? If OS X are you sure there are not crashlogs in `~/Library/Logs/DiagnosticReports/` after this error?  If Linux no evidence of a crash in `/var/log/kern.log`? Also what do you mean by `my stacks usually don't touch mapnik when tm2 crashes`?

**Comment by mojodna** [comment] 2014-04-02 23:27
OS X 10.9.2 w/ tm2@HEAD (node-0.10.26).  Nothing in `~/Library/Logs/DiagnosticReports/`.

The stack traces I've seen when this happens haven't included `tilelive-vector` (the one from @nickidlugash does).  Sometimes it'll just do this when I first load the app (before it gets to loading CSS).  I'm unable to reproduce it consistently though.

IOW, this may be 2 separate issues: `TypeError: Cannot read property '0' of undefined` (which causes TM2 to die immediately, potentially interrupting a Mapnik operation and causing the segfault) and the segfault.

**Comment by springmeyer** [comment] 2014-04-03 01:30
okay, thanks. Yes, I think this could be separate but related issues. @makella is hitting the same error as you except with a segfault in addition:

```
TypeError: Cannot read property '0' of undefined
    at paramCallback (/tm2-osx-2014-03-28-47d4e6a/tm2/node_modules/express/lib/router/index.js:146:30)
    at done (/tm2-osx-2014-03-28-47d4e6a/tm2/index.js:114:25)
    at /tm2-osx-2014-03-28-47d4e6a/tm2/lib/style.js:63:29
    at /tm2-osx-2014-03-28-47d4e6a/tm2/lib/style.js:136:25
    at /tm2-osx-2014-03-28-47d4e6a/tm2/lib/source.js:79:25
    at /tm2-osx-2014-03-28-47d4e6a/tm2/lib/source.js:319:29
    at Get.<anonymous> (/tm2-osx-2014-03-28-47d4e6a/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:287:25)
    at Get.<anonymous> (/tm2-osx-2014-03-28-47d4e6a/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:181:33)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:92:17)
/tm2-osx-2014-03-28-47d4e6a/start.command: line 2: 32064 Segmentation fault: 11  ${CURRENT_DIRECTORY}/tm2/node ${CURRENT_DIRECTORY}/tm2/index.js
logout
```

**Comment by makella** [comment] 2014-04-03 17:03
@springmeyer just wanted to let you know this happened again this time after I had made some changes to `project.yml` (for layer ordering) and then restarted TM2.  I stopped TM2 before editing `project.yml`

From my Terminal window:

```
TM2 @ http://localhost:3000/

TypeError: Cannot read property '0' of undefined
    at paramCallback (/tm2-osx-2014-03-28-47d4e6a/tm2/node_modules/express/lib/router/index.js:146:30)
    at done (/tm2-osx-2014-03-28-47d4e6a/tm2/index.js:114:25)
    at /tm2-osx-2014-03-28-47d4e6a/tm2/lib/style.js:101:25
    at /tm2-osx-2014-03-28-47d4e6a/tm2/lib/style.js:136:25
    at /tm2-osx-2014-03-28-47d4e6a/tm2/lib/source.js:79:25
    at /tm2-osx-2014-03-28-47d4e6a/tm2/lib/source.js:319:29
    at Get.<anonymous> (/tm2-osx-2014-03-28-47d4e6a/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:287:25)
    at Get.<anonymous> (/tm2-osx-2014-03-28-47d4e6a/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:181:33)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:92:17)
logout

[Process completed]
```

**Comment by springmeyer** [comment] 2014-04-04 05:51
Thanks @makella. Interesting to see that there appears not to have been a segfault at the end of that. That starts to point to the segfault being a random result rather than the cause of this.

**Comment by pantierra** [comment] 2014-04-19 17:48
Just did a fresh installation from the master branch and used only the out of the box Mapbox Streets V4 source. I was playing around to see the changes between the stable version and the new tm2. Unfortunately it is crashing now and then, especially when going into the source configuration, with a similar error, if not the same, as @makella is reporting:

TypeError: Cannot read property '0' of undefined
    at paramCallback (/home/felix/programs/tm2/node_modules/express/lib/router/index.js:146:30)
    at done (/home/felix/programs/tm2/index.js:154:25)
    at /home/felix/programs/tm2/lib/source.js:143:25
    at /home/felix/programs/tm2/lib/source.js:319:29
    at Get.<anonymous> (/home/felix/programs/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:287:25)
    at Get.<anonymous> (/home/felix/programs/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:181:33)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:92:17)
    at Socket.emitTimeout (http.js:1797:10)
    at Socket.g (events.js:180:16)

**Comment by springmeyer** [comment] 2014-04-23 20:06
@xamanu - generally it seems like this error is happening when the network connection drops. So you can likely work around for now by making sure your wifi is solid :)

**Comment by yhahn** [comment] 2014-05-16 11:33
I haven't seen this in a while now. Closing.

**Closed as completed by yhahn** 2014-05-16 11:33 UTC
Labels: bug
