### ISSUE TITLE
publishing to Mapbox

### ISSUE THREAD

**Issue by jqtrde** [mapbox/mapbox-studio-classic#84] opened 2013-12-07 17:10 UTC
I'd love be able to be able to publish tiles generated with TM2 to Mapbox. Is there a means to do that?

Hack-ey solutions are welcome!

**Comment by yhahn** [comment] 2013-12-07 17:15
Yes, coming soon : )

**Comment by jqtrde** [comment] 2013-12-07 17:18
:metal:

Any ideas on timeframe? Getting ready to start a new project, would like to use TM2, but will use the original if this is still a few months off.

**Comment by wprater** [comment] 2014-01-31 05:12
wanting to push vector tile styles to mapbox too!  any news?

**Comment by samanpwbb** [comment] 2014-04-02 17:29
Duplicate of https://github.com/mapbox/tm2/issues/258

**Closed as completed by samanpwbb** 2014-04-02 17:29 UTC
